### PR TITLE
Make v8py.Context a Python context manager

### PR DESCRIPTION
**Pull request by buffer**

### CODE REVIEW

**Comment by tbodt** [comment]
Why is it useful for Context to be a context manager?

**Comment by tbodt** [comment]
Also, creating a context fails on Python 3:
```
self = <v8py.context.Context object at 0x7ff3ba7d0518>
args = (<class 'test_global.Global.<locals>.Global'>,), kwargs = {}
    def __init__(self, *args, **kwargs):
>       _v8py.Context.__init__(self, *args, **kwargs)
E       TypeError: object.__init__() takes no parameters
v8py/context.py:5: TypeError
```

**Comment by buffer** [comment]
Context as a context manager could be useful so that it can be used directly in  _with_ statement without first having to be wrapped by _contextlib.closing()_. Apart from being a Pythonic approach, it would also allow to manage some initialization/destruction details transparently in the next future if needed.

**Comment by tbodt** [comment]
In v8py, contexts don't need to be opened or closed, they can just be used.

**Pull request closed without merging**
